name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  macos:
    name: macOS
    runs-on: macos-11
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Cache cmake build
        uses: actions/cache@v3
        with:
          path: build
          key: macos-cmake-v3
      - name: Configure
        run: | 
          cmake \
            -B build \
            -D CMAKE_BUILD_TYPE=RelWithDebInfo \
            # EOL
      - name: Build
        run: | 
          cmake \
            --build build \
            -j $(sysctl -n hw.physicalcpu) \
            --target package \
            # EOL
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: yuri-macos.dmg
          path: build/yuri-macos.dmg
          retention-days: 7
